=== DylaanBH9/lmsgi-recetas-Dylan-Bauti-Huelva/recetas.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="menu">
        <xs:complexType>
                <xs:sequence>
                <xs:element name="receta">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre"  type="xs:string"/>
                            <xs:element name="categoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Entrante"/>
                                        <xs:enumeration value="Principal"/>
                                        <xs:enumeration value="Postre"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tiempo"  type="xs:integer"/>
                            <xs:element name="dificultad"    type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DylaanBH9/lmsgi-recetas-Dylan-Bauti-Huelva/recetas.xml
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="recetas.xsd">
    <receta id="001">
        <nombre>Croquetas</nombre>
        <categoria>Entrante</categoria>
        <tiempo>5</tiempo>
        <dificultad>Fácil</dificultad>
    </receta>
    <receta id="002">
        <nombre>Paella</nombre>
        <categoria>Principal</categoria>
        <tiempo>30</tiempo>
        <dificultad>Difícil</dificultad>
    </receta>

    <receta id="003">
        <nombre>Helado de Vainilla</nombre>
        <categoria>Postre</categoria>
        <tiempo>15</tiempo>
        <dificultad>Medio</dificultad>
    </receta>
</menu>
